# Generated by Django 4.2.11 on 2024-06-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_student_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, to='admin_panel.class'),
        ),
    ]
