# Generated by Django 4.2.11 on 2024-06-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_teacher_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='courses',
            field=models.ManyToManyField(blank=True, to='admin_panel.course'),
        ),
    ]
