# Generated by Django 4.2.11 on 2024-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_classcourseteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classcourseteacher',
            name='course_id',
        ),
        migrations.AddField(
            model_name='classcourseteacher',
            name='courses',
            field=models.ManyToManyField(to='admin_panel.course'),
        ),
    ]
