# Generated by Django 4.2.11 on 2024-06-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_remove_classcourseteacher_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='exams',
            field=models.ManyToManyField(blank=True, to='admin_panel.exam'),
        ),
    ]
