# Generated by Django 4.2.11 on 2024-06-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_student_password_teacher_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='student',
            name='face_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
