# Generated by Django 4.2.11 on 2024-06-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_remove_student_password_student_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_faces/'),
        ),
    ]
