# Generated by Django 4.2.11 on 2024-06-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_alter_student_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
