# Generated by Django 5.0.6 on 2024-06-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_remove_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registration_no',
        ),
    ]
