# Generated by Django 4.2.11 on 2024-06-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
